@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/laravel.puml
!include DEVICONS/mysql.puml
!include FONTAWESOME/users.puml

Person(farmaceutico, "Farmacêutico/Funcionário", "Gerencia e consulta medicamentos", $sprite="users")

System(system, "Sistema de Gerenciamento de Medicamentos", "Gerencia operações de medicamentos")

System_Ext(oauth, "Google OAuth 2.0", "Autenticação de Usuários")

Rel(farmaceutico, system, "Gerencia/Consulta medicamentos")
Rel(system, oauth, "Autenticação de Usuários")

@enduml
